### ISSUE TITLE
cant get jack to work

### ISSUE THREAD

**Issue by bacenote** [flathub/com.bitwig.BitwigStudio#1]
Hello, sorry if this is the wrong place for the question, but I am not able to get jack working from this bitwig flatpak. Is bitwig not able to talk to jack because its sandboxed?

OS is manjaro 21.0.1 and tired both jack and jack2

Thanks for your work in making Bitwig available now to a whole lot more linux distros.

**Comment by abique** [comment]
Yes it is alright to report that issue here.
When using bitwig via flatpak you must use pipewire instead of jack itself.
pipewire can provide a transparent jack replacement.

**Comment by dal00** [comment]
I think that would be pretty good info to include in the description on Flathub.

**Comment by unholyeyebrows** [comment]
Hi. Firstly a huge thanks for producing a Flatpak of Bitwig. Great to be able to install it on pretty much any distro!

I am trying it out on Fedora Silverblue 34 Beta which defaults to Pipewire out of the box. However when I select Jack as Bitwig's output my song will play but I hear no audio. Switching back to Alsa or Pulseaudio works fine. Might I be missing something obvious here? Happy to collect some debug info if it would help.

Thanks
Nick

**Comment by hfiguiere** [comment]
There was also a bug in the freedesktop runtime that broke pipewire. Make sure you have the latest.
