### ISSUE TITLE
Bitwig 3.3 branch missing from flathub

### ISSUE THREAD

**Issue by tesfabpel** [flathub/com.bitwig.BitwigStudio#10]
I have a license for Bitwig 3.3 but `flatpak update` complains that it can't find 3.3 on the flathub remote.

```
F: Warning: Treating remote fetch error as non-fatal since app/com.bitwig.BitwigStudio/x86_64/3.3 is already installed: No such ref 'app/com.bitwig.BitwigStudio/x86_64/3.3' in remote flathub
Nothing to do.
```
Running `flatpak remote-ls` shows that indeed there is only the stable branch in the repository.
Is it possible to add it back?

**Comment by hfiguiere** [comment]
Seems the repos were removed at the request of the authors:

https://github.com/flathub/flathub/issues/2922

So would say this is the expected behaviour for flatpak/flathub.
