### ISSUE TITLE
Can't open or save files due to error in /app/bin/show-file-dialog-gtk3

### ISSUE THREAD

**Issue by daviwil** [flathub/com.bitwig.BitwigStudio#12]
Hi!  Thanks so much for putting together this build of Bitwig, it works almost perfectly except for one issue:

When I try to open or save a file, nothing happens in the UI.  No dialog is shown, no error message, nothing.  When I run Bitwig using `flatpak run com.bitwig.BitwigStudio`, I see the following error when I try to open or save a file:

```
/app/bin/show-file-dialog-gtk3: symbol lookup error: /gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

The funny file path to `libpthread` is due to my use of Flatpak in the Guix distribution.

I don't have issues with file dialogs in other programs installed via Flatpak like Firefox or Chromium.  Seems to be specifically related to Bitwig and something with my configuration.

Any pointers on what I could try to diagnose or fix this issue?  Happy to try anything.

Here are the details about the build of Bitwig I have installed:

```
λ flatpak info com.bitwig.BitwigStudio

Bitwig Studio - Modern music production and performance

          ID: com.bitwig.BitwigStudio
         Ref: app/com.bitwig.BitwigStudio/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.4.3
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 510.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 6279957e74e9b860c1f6a36e254063bfb0eee71f04fa3e86c31b024133695624
      Parent: ab1f092c3d06cfd8501247a85c1e9335ffba81d616c9d897a84fc7d702df767b
     Subject: Publish 4.4.3 (a735114b)
        Date: 2022-11-15 09:18:10 +0000
```

Thanks!

**Comment by daviwil** [comment]
Hi @abique, apologies for the ping.  Do you have any advice on how I can diagnose the problem I described above?  I'm totally happy to do the investigation myself, I just need some insight into where the problem could be.

Thanks a lot!

**Comment by daviwil** [comment]
Any thoughts here?  I'm using glibc 2.33 so this symbol should still exist in `libpthread.so`.

**Comment by abique** [comment]
Hi, this is quite strange. I've supposed that it should use freedesktop's glibc.
:thinking:

**Comment by abique** [comment]
Maybe we should use a dbus service instead for file dialogs?

**Comment by daviwil** [comment]
Yes, I also thought it was strange that it doesn't use a glibc provided by Flatpak.  If a dbus service can be used it might be helpful!

**Comment by abique** [comment]
Do you know anything on how to open the file dialogs via dbus?

**Comment by daviwil** [comment]
Yep, the `xdg-desktop-portal` interface is the way I see other Flatpak applications do it.  Here's the `FileChooser` interface:

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser

**Comment by abique** [comment]
Thanks!

**Comment by daviwil** [comment]
After looking into this issue again, I finally discovered the root cause:  The `filesystem=host` permission was allowing the program to pick up the `glibc` install of my host machine instead of using the one inside of the Flatpak system.  Once I set the permission only to `filesystem=home`, the bundled `glibc` was used and I was able to launch file open/save dialogs successfully.  Everything seems to be working great now!

**Comment by hfiguiere** [comment]
> The `filesystem=host` permission was allowing the program to pick up the `glibc` install of my host machine instead of using the one inside of the Flatpak system.

I doubt that's the case.

**Comment by daviwil** [comment]
It certainly was the case for me.  I don't know if Guix builds Flatpak differently, but disabling `host` permission using Flatseal made the right `glibc` get loaded, no more message about missing `__libc_pthread_init` when I run Bitwig via Flatpak from the shell.
