### ISSUE TITLE
Older Bitwig versions as flatpaks?

### ISSUE THREAD

**Issue by gabrielbauman** [flathub/com.bitwig.BitwigStudio#16]
Hi there,

I purchased Bitwig Studio back in the 4.1 era, and I'd like to run it on my Fedora machine as a flatpak. Any chance we might get a flatpak for, say, 4.1.6?

Can't really install the .deb (fedora uses .rpm packaging) and trying to make one with alien failed for me.

Happy to build one myself, but there's no /flatpak/Bitwig-4.1.6.zip on the web site.

**Comment by abique** [comment]
Hi,

You can get older flatpak from here: https://www.bitwig.com/previous_releases/

Before the 4.3 we didn't have flatpak archiving, because flatpak was very new to us and it took sometime to do things right.

You could try to manually build this commit: https://github.com/flathub/com.bitwig.BitwigStudio/commit/62b809a0ef2f3469b44ccd261a40c6ca26fd3e7b to produce the 4.1.6 flatpak yourself.

Cheers,
Alex

**Comment by abique** [comment]
Ah sorry you didn't find the 4.1.6.zip, I didn't read correctly...
You can get the .deb here https://www.bitwig.com/dl/?id=469&os=installer_linux and then maybe adjust the build script?

Another solution for you would be to use this little script:

```bash
bw-install() (
    oldpwd="$PWD"
    suffix="$2"

    # if the suffix isn't empty, then prefix it with "-"
    if [[ ! -z "$suffix" ]] ; then
        suffix="-$suffix"
    fi

    instdir="$HOME/local/bitwig${suffix}"

    rm -rf "$instdir" &&
        mkdir -p "$instdir" &&
        cd "$instdir" &&
        if [[ -e "$1" ]] ; then
            ln -sf "$1" bw.deb
        elif [[ -e "$oldpwd/$1" ]] ; then
            ln -sf "$oldpwd/$1" bw.deb
        else
            wget "$1" -O bw.deb
        fi &&
        \bsdtar xf bw.deb &&
        \bsdtar xf data.tar.[gx]z &&
        rm bw.deb &&
        rm data.tar.[gx]z &&
        rm control.tar.* &&
        rm debian-binary &&
        echo "  ---" &&
        echo "  --- Bitwig Studio installed in $instdir" &&
        echo "  --- Launch using: $instdir/opt/bitwig-studio/bitwig-studio" &&
        echo "  ---"
)
```

I use it myself to extract the .deb and install it into `~/local/bitwig`.
