### ISSUE TITLE
No Sound via Output Device on Fedora 34 

### ISSUE THREAD

**Issue by Gambloide** [flathub/com.bitwig.BitwigStudio#2]
Hi. I just stumbled across this today and thought I'd give it a try.
Sadly, the audio output does not seem to work on my machine.
I haven't tried inputs.

**System**

OS: Fedora 34
Pipewire:  0.3.27-2.fc34
BitwigStudio Flatpak flavor: stable

**Steps to reproduce**

1. Install via `flatpak install flathub com.bitwig.BitwigStudio` in user mode and from stable branch.
2. Launch the application via `flatpak run com.bitwig.BitwigStudio`
3. Choose `DEMO MODE` in the popup
4. Press `install essentials` in the next popup and wait for it to finish
5. Press the overview button in the middle of the titlebar of the application
6. Choose `Play Keys` from the `Quick Start` menu
7. Enable capslock
8. Try to play on the virtual keyboard by pressing e.g. the `a` key

**Observation** 
The virtual instrument shows the keys being pressed and the master track shows sound being generated.
However, there is no sound output by the software.
Changing the output devices from default to specific ones in the setting also does not change them. 
Changing between Jack (via Pipewire) or ALSA also didn't change this.

The logs are also being filled with different exceptions from the application, most mentioning denied access to files, files not being found or `Jack client [memaddr]: not implemented [memaddr]` errors. Logs attached below. 

**Expected Behavior**
Sound picked up by the master track can be heard through the configured output device or the default output device.

**Logs**
Logs: https://gist.github.com/Gambloide/9569f9472663e997da41482b7bc565c3

**Comment by abique** [comment]
Hi,
Thank you for the detailed bug report.
Did you try to use pulse audio output?
ALSA should work as well, are you sure you selected the correct device?
We'd need the engine logs: `~/.BitwigStudio/log/engine.log`.

**Comment by Gambloide** [comment]
Sorry, I completely forgot about this, hence no updates. I wiped the Fedora installation shortly after raising this and have since not tried BitwigStudio anymore.
