### ISSUE TITLE
Bitwig 4.1.6 isn't runninganymore on my Fedora 35 (ldconfig failed)

### ISSUE THREAD

**Issue by mariushartig** [flathub/com.bitwig.BitwigStudio#7]
i did update to version 4.1.6 since that i will get this error
"bwrap: Can't mkdir /app/lib/i386-linux-gnu: Read-only file system
error: ldconfig failed, exit status 256"

**Comment by abique** [comment]
Ah I get the same error, maybe it is a bug in flatpak?

**Comment by abique** [comment]
I've pushed an update

**Comment by abique** [comment]
Fixed now.

**Comment by mariushartig** [comment]
thx, can i ask you what the problem was ?

**Comment by abique** [comment]
See the diff.
